# Generated by Django 3.1.5 on 2021-01-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='с большой буквы', max_length=150, verbose_name='Название олимпиады')),
                ('short_name', models.CharField(help_text='с большой буквы', max_length=50, verbose_name='Сокращенное название')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Олимпиада',
                'verbose_name_plural': 'Олимпиады',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='с большой буквы в одно слово', max_length=150, verbose_name='Название этапа')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_interval', models.CharField(help_text="дата месяц без года или 'пока не известно'", max_length=150, verbose_name='Даты проведения')),
                ('start_date', models.DateField(blank=True, help_text='дата-месяц-год', null=True, verbose_name='Начало этапа')),
                ('finish_date', models.DateField(blank=True, help_text='дата-месяц-год', null=True, verbose_name='Окончание этапа')),
                ('finished', models.BooleanField(default=False, verbose_name='Завершилась')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.olympiads', verbose_name='Олимпиада')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.stages', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Расписание олимпиад',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='2000-2001', max_length=15, verbose_name='Год проведения')),
                ('study_year', models.IntegerField(verbose_name='Класс')),
                ('task', models.CharField(max_length=150, verbose_name='Условия')),
                ('task_title', models.CharField(default='у', max_length=150, verbose_name='Название для таблицы')),
                ('solution', models.CharField(max_length=150, verbose_name='Решения')),
                ('solution_title', models.CharField(default='р', max_length=150, verbose_name='Название для таблицы')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.olympiads', verbose_name='Олимпиада')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.stages', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
    ]
