# Generated by Django 3.1.5 on 2021-01-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание'},
        ),
        migrations.AlterField(
            model_name='materials',
            name='solution_title',
            field=models.CharField(default='р', help_text='возможные варианты: р р(7-9) и др. по ситуации', max_length=150, verbose_name='Название для таблицы'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='study_year',
            field=models.IntegerField(help_text='с 7 по 11', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='task',
            field=models.CharField(help_text='ссылка', max_length=150, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='task_title',
            field=models.CharField(default='у', help_text='возможные варианты: у у(7-9) у-р и др. по ситуации', max_length=150, verbose_name='Название для таблицы'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='year',
            field=models.CharField(help_text='например 2000-2001', max_length=15, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_interval',
            field=models.CharField(help_text="дата, месяц без года или 'пока не известно'", max_length=150, verbose_name='Даты проведения'),
        ),
    ]
