# Generated by Django 3.1.5 on 2021-01-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0003_auto_20210110_2342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materials',
            unique_together={('olympiad', 'stage', 'year', 'study_year', 'task', 'solution')},
        ),
    ]
