# Generated by Django 3.1.5 on 2021-01-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0004_auto_20210111_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiads',
            name='title',
            field=models.CharField(help_text='с большой буквы', max_length=150, unique=True, verbose_name='Название олимпиады'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='title',
            field=models.CharField(help_text='с большой буквы в одно слово', max_length=150, unique=True, verbose_name='Название этапа'),
        ),
    ]
