# Generated by Django 3.1.5 on 2021-01-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0005_auto_20210111_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='solution_title',
            field=models.CharField(blank=True, help_text='возможные варианты: р р(7-9) и др. по ситуации', max_length=150, verbose_name='Название для таблицы'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='task_title',
            field=models.CharField(default='у', help_text='возможные варианты: у у(7-9) у-р у-о и др. по ситуации', max_length=150, verbose_name='Название для таблицы'),
        ),
    ]
