# Generated by Django 3.1.5 on 2021-01-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0006_auto_20210111_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stages',
            name='title',
            field=models.CharField(help_text='с большой буквы без слова этап', max_length=150, unique=True, verbose_name='Название этапа'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('olympiad', 'stage', 'start_date', 'finish_date')},
        ),
    ]
