# Generated by Django 3.1.5 on 2021-01-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0007_auto_20210111_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_content', models.CharField(max_length=150, verbose_name='Контент новости')),
                ('show', models.BooleanField(default=True, verbose_name='Отобразить')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
