# Generated by Django 3.1.5 on 2021-01-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='с большой буквы', max_length=150, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='с большой буквы', max_length=150, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_year', models.IntegerField(verbose_name='Класс')),
                ('video_link', models.CharField(blank=True, max_length=300, verbose_name='Ссылка на видео')),
                ('theory', models.TextField(verbose_name='Теоретический материал')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.sections', verbose_name='Раздел')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topics', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_year', models.IntegerField(verbose_name='Класс')),
                ('task', models.TextField(verbose_name='Задание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/learning', verbose_name='Иллюстрация')),
                ('answer', models.CharField(max_length=500, verbose_name='Ответ')),
                ('solution', models.TextField(blank=True, verbose_name='Решение')),
                ('video_solution_link', models.CharField(blank=True, max_length=300, verbose_name='Видео разбор')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.sections', verbose_name='Раздел')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topics', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
